include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    no_leading_underscores_for_local_identifiers: false
    prefer_null_aware_operators: false
    unnecessary_brace_in_string_interps: false
    unnecessary_string_interpolations: false
    unnecessary_to_list_in_spreads: false
    use_build_context_synchronously: false