// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzWSUOuszP-cvg5ZPbkPPzFP8MvmQORGU',
    appId: '1:851087972500:web:60c952458fd06c1e1bbc81',
    messagingSenderId: '851087972500',
    projectId: 'gradeflow-20260113',
    authDomain: 'gradeflow-20260113.firebaseapp.com',
    storageBucket: 'gradeflow-20260113.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO84c5hmXVnK7ONPNKy8KRhr9XtlkcvgU',
    appId: '1:851087972500:android:5d338f2689c117b21bbc81',
    messagingSenderId: '851087972500',
    projectId: 'gradeflow-20260113',
    storageBucket: 'gradeflow-20260113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdfKnTeWevfpNVtVYN1queR6JzFD-ExQ',
    appId: '1:851087972500:ios:c468bbe668be3fa41bbc81',
    messagingSenderId: '851087972500',
    projectId: 'gradeflow-20260113',
    storageBucket: 'gradeflow-20260113.firebasestorage.app',
    iosBundleId: 'com.gradeflow.app',
  );

}